services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  minio:
    image: 'minio/minio:latest'
    container_name: 'minio-1'
    environment:
      - 'MINIO_ROOT_USER=dominion'
      - 'MINIO_ROOT_PASSWORD=dominion'
    ports:
      - "9000:9000"
    command: 'server /data'